#FAKE NEWS DETECTION

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import re
import string
#re for removing chars from text

In [ ]:
df_fake=pd.read_csv("Fake.csv")
df_true=pd.read_csv("True.csv")

In [ ]:
df_fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  
0  December 31, 2017  
1  December 31, 2017  
2  December 30, 2017  
3  December 29, 2017  
4  December 25, 2017

In [ ]:
df_true.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017   
2  December 31, 2017   
3  December 30, 2017   
4  December 29, 2017

In [ ]:
df_fake["class"]=0
df_true["class"]=1

In [ ]:
df_fake.shape,df_true.shape

((23481, 5), (21417, 5))

In [ ]:
df_fake_manual_testing=df_fake.tail(10)
for i in range(23480,23470,-1):
  df_fake.drop([i],axis=0,inplace=True)
df_true_manual_testing=df_true.tail(10)
for i in range(21416,21406,-1):
  df_true.drop([i],axis=0,inplace=True)


In [ ]:
df_manual_testing=pd.concat([df_fake_manual_testing,df_true_manual_testing],axis=0)
df_manual_testing.to_csv("manualtesting.csv")

In [ ]:
#created manual testing file from 10 rows of both

In [ ]:
df_merge=pd.concat([df_fake,df_true],axis=0)
df_merge.head(10)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   
5   Racist Alabama Cops Brutalize Black Boy While...   
6   Fresh Off The Golf Course, Trump Lashes Out A...   
7   Trump Said Some INSANELY Racist Stuff Inside ...   
8   Former CIA Director Slams Trump Over UN Bully...   
9   WATCH: Brand-New Pro-Trump Ad Features So Muc...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   
5  The number of cases of cops brutalizing and ki...    News   
6  Donald Trump spent a good portion of his day a...    News   
7  In the wake of yet another court decision that...    News   
8  Many people have raised the alarm regarding th...    News   
9  Just when you might have thought we d get a br...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0  
5  December 25, 2017      0  
6  December 23, 2017      0  
7  December 23, 2017      0  
8  December 22, 2017      0  
9  December 21, 2017      0

In [ ]:
df=df_merge.drop(["title","subject","date"],axis=1)
df.head(10)

text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0
5  The number of cases of cops brutalizing and ki...      0
6  Donald Trump spent a good portion of his day a...      0
7  In the wake of yet another court decision that...      0
8  Many people have raised the alarm regarding th...      0
9  Just when you might have thought we d get a br...      0

In [ ]:
df=df.sample(frac=1)

In [ ]:
df.head(10)

text  class
8252   WASHINGTON (Reuters) - Supporters of Merrick G...      1
10794  SPRINGFIELD, Ill. (Reuters) - Illinois Republi...      1
10172  The publication that just can t seem to get ov...      0
4676   WASHINGTON (Reuters) - Republican U.S. Represe...      1
3257   SAN JUAN (Reuters) - The economically struggli...      1
14280  The Senate had better stick to their guns on t...      0
11738  Opposing views and beliefs has much of this co...      0
2400   WASHINGTON (Reuters) - Congressional Republica...      1
8698   What s happening in Flint, Michigan is beyond ...      0
16715  MOSCOW (Reuters) - A Russian serviceman in the...      1

In [ ]:
df.isnull().sum() #no null values

text     0
class    0
dtype: int64

In [ ]:
#Remove unnecessary characters

In [ ]:
def word_drop(text):
  text=text.lower()
  text=re.sub('\[.*?\]','',text)
  text=re.sub("\\W"," ",text)
  text=re.sub('https?://\S+|www\.\S+','',text)
  text=re.sub('<.*?>+','',text)
  text=re.sub('[%s]'% re.escape(string.punctuation),'',text)
  text=re.sub('\n','',text)
  text=re.sub('\w*\d\w*','',text)
  return text

In [ ]:
df["text"]=df["text"].apply(word_drop)

In [ ]:
df.head(10)

text  class
8252   washington  reuters    supporters of merrick g...      1
10794  springfield  ill   reuters    illinois republi...      1
10172  the publication that just can t seem to get ov...      0
4676   washington  reuters    republican u s  represe...      1
3257   san juan  reuters    the economically struggli...      1
14280  the senate had better stick to their guns on t...      0
11738  opposing views and beliefs has much of this co...      0
2400   washington  reuters    congressional republica...      1
8698   what s happening in flint  michigan is beyond ...      0
16715  moscow  reuters    a russian serviceman in the...      1

In [ ]:
x=df["text"]
y=df["class"]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
vectorization=TfidfVectorizer()
xv_train=vectorization.fit_transform(x_train)
xv_test=vectorization.transform(x_test)


#Logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
LR=LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [ ]:
LR.score(xv_test,y_test) #98% accurate

0.986541889483066

In [ ]:
pred_LR=LR.predict(xv_test)

In [ ]:
print(classification_report(y_test,pred_LR))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5849
           1       0.98      0.99      0.99      5371

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220



In [ ]:
pred_LR

array([0, 0, 0, ..., 0, 1, 1])

#Decisison tree classification

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
DT=DecisionTreeClassifier()
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

In [ ]:
DT.score(xv_test,y_test) #99% accurate

0.9959893048128342

In [ ]:
pred_DT=DT.predict(xv_test)

In [ ]:
print(classification_report(y_test,pred_DT))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      5849
           1       1.00      0.99      1.00      5371

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220



#Gradient Boosting Classifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
GBC=GradientBoostingClassifier(random_state=0)
GBC.fit(xv_train,y_train)

GradientBoostingClassifier(random_state=0)

In [ ]:
GBC.score(xv_test,y_test)


0.9955436720142602

In [ ]:
pred_GBC=GBC.predict(xv_test)

In [ ]:
print(classification_report(y_test,pred_GBC))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      5849
           1       0.99      1.00      1.00      5371

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220



In [ ]:
pred_GBC

array([0, 0, 0, ..., 0, 1, 0])

#Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
RFC=RandomForestClassifier(random_state=0)
RFC.fit(xv_train,y_train)

RandomForestClassifier(random_state=0)

In [ ]:
RFC.score(xv_test,y_test)

0.988680926916221

In [ ]:
pred_RFC=RFC.predict(xv_test)

In [ ]:
print(classification_report(y_test,pred_RFC))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5849
           1       0.99      0.99      0.99      5371

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220



In [ ]:
pred_RFC

array([0, 0, 0, ..., 0, 1, 0])

#Manual Testing

In [ ]:
def output_lable(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"

def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(word_drop)
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)
    pred_LR = LR.predict(new_xv_test)
    pred_DT = DT.predict(new_xv_test)
    pred_GBC = GBC.predict(new_xv_test)
    pred_RFC = RFC.predict(new_xv_test)

    return print("\n\nLR Prediction: {} \nDT Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(output_lable(pred_LR[0]),
                                                                                                              output_lable(pred_DT[0]),
                                                                                                              output_lable(pred_GBC[0]),
                                                                                                              output_lable(pred_RFC[0])))

In [ ]:
news = str(input())
manual_testing(news)